### ISSUE TITLE
CORS error on deployed version

### ISSUE THREAD

**Issue by bogdancrisu** [spokestack/node-spokestack#20]
### Describe the bug

Access to fetch at 'https://s.spokestack.io/u/-----/js/encode/model.json' from origin 'http://ip:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

### Environment

- Version of spokestack/client 14
- Node.js 15

### Expected behavior

Able to access NODE BASE URL from a domain or ip

### Actual behavior

Can't fetch NODE BASE URL from a domain or ip

**Comment by bogdancrisu** [comment]
Can I get some help with this, please?

**Comment by timmywil** [comment]
Sorry for the late reply. I'm the main author for node and was on vacation. I can reproduce this in our example app. That said, while ip:3000 is not working, localhost:3000 does, as do our websites that use node-spokestack, so if you double check that localhost is the right ip, that should respond with the appropriate CORS header. This would also not affect your production website, which I assume would make the request with a readable domain and not an IP address. Anyway, we'll look into supporting this.

**Comment by timmywil** [comment]
We looked into changing the CORS header to allow all domains, but our URL shortener is built into our API and it would have the side-effect of enabling CORS for all API requests, which we don't want to do for security reasons. The best option here is to either proxy the requests through your node server or use the cloudfront URL directly as the baseUrl, which you can get from following the redirects. If there are enough requests for this, it's possible we'll separate the URL shortener from the API in the future, but I can't promise that. Sorry I couldn't be more help.

P.S. While these options will allow you to download the models using an IP address, keep in mind that most browsers disable `getUserMedia` - the api used to record - when not using https, except in the case of localhost. Note that `getUserMedia` will probably not be available for a local server using an IP address as the domain, so this may all be moot anyway.
